### ISSUE TITLE
Kodi screen reader makes Kodi 17 crash on OS X

### ISSUE THREAD

**Issue by falcon03** [ruuk/service.xbmc.tts#13]
Running Kodi 17 RC 3 on OS X 10.12 with Kodi screen reader enabled causes Kodi to crash. Changing the skin back to confluence in guisettings.xml does not help. :(

Any tip on how to determine what's causing the crash? I'd have no problems getting my hands dirty with code if needed. From the debug log I see that the crash happens somewhere after the instantiation of the OS X say backend.

**Comment by falcon03** [comment]
Crash occurs even with the Kodi 17 stable release..

I also tried doing a clean Kodi 17 installation, but in that case after placing the addon in %userdata/addons it never starts. Of course installing it via the GUI is not an option...

@ruuk, any idea?

**Comment by cljnco** [comment]
Hello, Running win 10 and 7 and recently upped to 17 on both. I am not experiencing any crashing. Uninstalling and reinstalling does not necessarily remove these folders. Please try manually removing Kodi TTS and the user data folder. You can locate the user data folder at "%appdata%\Kodi\userdata\addon_data\service.xbmc.tts", and the Kodi TTS folder at "%appdata%\Kodi\addonsservice.xbmc.tts"

Then reinstalling Kodi TTS from scratch off of the official repo. If that doesn't work your going to need to ask for help in the Forum where you can post a log file.

**Comment by falcon03** [comment]
@cljnco done all that without success. As I said, if I do a clean installation, meaning that I remove *every* trace of Kodi from the system, the Kodi screen reader won't start at all. If I try updating my existing installation, which contains only the Kodi screen reader add-on, Kodi crashes.

I've already tried asking in the forum, but got no useful reply.

**Comment by cljnco** [comment]
Are you Kalen on the forum? When you do a complete wipe and reinstall are you running any other addons or have you tried it only with KodiTTS? Is it crashing with SAPI or are you using another screen reader?

**Comment by ruuk** [comment]
@falcon03: Sorry I haven't responded sooner but I've been super busy. I've recently been given a Mac to use so this will be the first time I've been able to do any real testing with OSX. I'll try to set aside some time this month to see if I can duplicate your issue, but in the meantime a Kodi log would definitely be a useful first step.

**Comment by falcon03** [comment]
[kodi-debug.log.txt](https://github.com/ruuk/service.xbmc.tts/files/768852/kodi-debug.log.txt)@ruuk, attached a debug log. In the meantime I've found out that a friend of mine is running Kodi 17 on an iMac and the add-on is working fine...

**Comment by falcon03** [comment]
@ruuk: any update on this? Can you see where the issue is from the attached log?

I dug into the codebase, but I'm having a hard time figuring out where the crash occurs.

**Comment by ruuk** [comment]
Thanks for the log but there is nothing useful it it, which is often true of crashes of this sort. I'll do some testing myself when I get the chance.

**Comment by falcon03** [comment]
@ruuk I had the same feelings. I can paste the crash report that Mac OS spits out, but be ware that the crashing thread (number 21) doesn't get symbolicated. :(

I've also noticed that the add-on might benefit from more extensive debug/verbose logging; could you be interested in a PR to implement that?

**Comment by falcon03** [comment]
@ruuk, just another 2 cents. Kodi screen reader makes even Kodi 16.1 crash on Mac OS. However, while in Kodi 17.1 it crashes Kodi on the first launch, in Kodi 16.1 it makes Kodi crash only if you stop the add-on and restart it again. Logs and crash error are exactly the same.

Could this be caused by a race condition during the add-on startup process?

**Comment by falcon03** [comment]
@ruuk and all: I managed to get it working. It's an "hackaround" rather than a fix, but it looks like it's fine until we can track down the issue. Basically since the problem lies into the OSXSay backend instantiation, I made the VoiceOver backend work. It's a little bit less performant than the OSXSay one, but it doesn't crash.

However there's some work to do to make the add-on support Kodi 17 properly: OS D controls are no longer manageable, the PVR section needs some adjustments and support for the Estuary skin needs to be improved, not to mention sections that I haven't explored yet such as the weather section and the Add-On browser.

I think I'm going to give a shot at improving Kodi 17 support in the next days, but I won't be able to fix the OSXSay backend: in fact, when I run Kodi after attaching LLDB to it, if the add-on crashes VoiceOver freezes and I am not able to inspect stack traces to see what's causing the issue. But I feel there's something pretty nasty going on there...

**Comment by ruuk** [comment]
I've fixed this issue with https://github.com/ruuk/backends/commit/1a373d20d8b099d4579e1c6676d1b33e8def9259  by reverting to the old method of calling say in a subprocess. Unfortunately we lose the voice, speed and volume settings, but at least it doesn't crash.

I'm closing this issue. Please feel free, if you want, to create a new issue for a VoiceOver backend, PR a new backend in the backends repo or share any code you may have.

It's on my agenda to revisit this when I have some time, but for now I'll focus on the other issues with Estuary and the latest Kodi version.

**Comment by ruuk** [comment]
Just remembered you already have a VoiceOver issue :smile:
