### ISSUE TITLE
service.xbmc.tts french language

### ISSUE THREAD

**Issue by mhb01** [ruuk/service.xbmc.tts#16]
I am French. I want the voice service.xbmc.tts to speak in French please?

**Comment by ruuk** [comment]
It works in French for me using espeak and setting the voice to french.

The add-on should work for any language as long as a) Kodi is set to the correct language, and b) The speech engine in use can handle the language. There is nothing the add-on needs to do special for other language other than providing it's own translations for it's settings dialogs, which I am happy to do when someone provides me with those translations.

If using another language is causing errors when you use the add-on, that is another issue. I'll need a log in that case. I'm closing this issue. Feel free to open a new one if you have other issues. If you just have questions, please use the forum thread at https://forum.kodi.tv/showthread.php?tid=196757
