### ISSUE TITLE
Add Italian translation

### ISSUE THREAD

**Issue by falcon03** [ruuk/service.xbmc.tts#6]
I tried Kodi screen reader on OS X and I enjoyed it so much that I've decided to translate it in Italian, my native language. My translation is based on the English localization strings file, but they're dated December 2013. Have there been any updates to strings in the meanwhile? If so, could you provide me with a .pot file for them?

Of course, I'll attach a patch as soon as I finish translating the strings. I'm now in the process of "fine-tuning" some strings based on their context.

**Comment by ruuk** [comment]
That's great. I look forward to adding the translation.

**Comment by falcon03** [comment]
Hi,

sorry for the delay; I've now completed the translation. How do you prefer me to upload it? It looks like github won't let me upload any file whose type is different from jpggif/png...

BTW, I plan to maintain this translation for future updates! :-)

**Comment by falcon03** [comment]
Ok, looks like github does not allow to attach arbitrary files to issue comments. Here's a dropbox link to the strings.po file:

https://dl.dropboxusercontent.com/u/27567738/strings.po

Let me know if you prefer any other way to get the file in the future...

**Comment by ruuk** [comment]
Thanks. The preferred way would be to clone my repo, add the file, and
create a pull request, but this is fine too :)

**Comment by falcon03** [comment]
Ok. I'll do that in the future: I haven't still learnt the whole pull Request thing! :-)

BTW, could I ask when a new release including this translation is planned? I plan on recording some podcasts in Italian and people will start asking for this information...

**Comment by ruuk** [comment]
I'll try to do it today.

**Comment by falcon03** [comment]
wow, that's awesome! :-)

**Comment by ruuk** [comment]
Added :)
